export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const SET_TRAINING_PLAN = 'SET_TRAINING_PLAN';
export const SET_EXERCISE_COMPLETED = 'SET_EXERCISE_COMPLETED';
export const SET_EXERCISE_INCOMPLETE = 'SET_EXERCISE_INCOMPLETE';
export const SET_SELECTED_EXERCISE = 'SET_SELECTED_EXERCISE';
export const SET_SELECTED_DAY_INDEX = 'SET_SELECTED_DAY_INDEX';
export const SET_SELECTED_WEEK_INDEX = 'SET_SELECTED_WEEK_INDEX';
export const SET_SELECTED_YEAR = 'SET_SELECTED_YEAR';